package kaboom.logic;

public enum KEYWORD_TYPE {
	INVALID, TASKID, 
	TASKNAME, MODIFIED_TASKNAME, 
	START_DATE, START_TIME, END_DATE, END_TIME, DATE,
	PRIORITY, 
	VIEWTYPE, 
	SORT,
	UNKNOWN
}
